#!/bin/bash

die() {
	echo died
	exit 1
}

trap die sigint
trap die sigquit
trap die sigterm

for cmd in 8086 necv20 286 386 486 586 586pro 686 all all_x64; do
	echo Testing $cmd
	timeout 15s ./fuzz-random-test $cmd >/dev/null 2>&1 </dev/null; X=$?
	if [[ "$X" == 124 || "$X" == 0 ]]; then true; else exit 1; fi
done

