#!/bin/bash
# sort of like svn-update-all
declare WORKDIR="${1:-.}"
pushd "${WORKDIR}"

make clean 2>/dev/null
make distclean 2>/dev/null
"$(dirname "$0")"/cleantree 2>/dev/null
for i in \* \*/\* \*/\*/\*; do git add $i 2>/dev/null; done
git commit -a
"$(dirname "$0")"/cleantree 2>/dev/null

